version: '3'

services:
  registry:
    container_name: registry
    image: registry:2
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./auth:/auth
      - ./registry/storage:/var/lib/registry
      - ./registry/config.yml:/etc/docker/registry/config.yml

  registry-ui:
    container_name: registry-ui
    image: joxit/docker-registry-ui:static
    restart: always
    environment:
      - REGISTRY_URL=http://registry:5000
      - DELETE_IMAGES=true
