version: '3'

services:
  registry:
    container_name: registry
    image: registry:2
    restart: always
    ports:
      - 443:443
    volumes:
      - ./auth:/auth
      - ./certs:/certs
      - ./registry/storage:/var/lib/registry
      - ./registry/config.yml:/etc/docker/registry/config.yml
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/registry.key
      - REGISTRY_HTTP_ADDR=0.0.0.0:443

  registry-ui:
    container_name: registry-ui
    image: joxit/docker-registry-ui:static
    restart: always
    environment:
      - REGISTRY_URL=https://registry:443
      - DELETE_IMAGES=true
